artifact_uri: file:///c:/Users/crist/Documents/anyoneai/finalprojectFrontAnyoneAI/dynamic-form/mlruns/0/93c9d5110ad34c91ac778aa0c88eb2b4/artifacts
end_time: 1685901814063
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 93c9d5110ad34c91ac778aa0c88eb2b4
run_name: LightGBM_trial
run_uuid: 93c9d5110ad34c91ac778aa0c88eb2b4
source_name: ''
source_type: 4
source_version: ''
start_time: 1685901810536
status: 3
tags: []
user_id: crist
